import csv


def makeunique_multi(l):
    check = set()
    res = []
    for i in l:
        x = ''
        for j in i:
            x = x + (j)
        if not x in check:
            res.append(i)
            check.add(x)
        else:
            pass
    return res


lUnknownDecks = [['p.e.k.k.a', 'mega knight', 'zap', 'bandit', 'baby dragon', 'princess', 'arrows', 'archers'],
                 ['p.e.k.k.a', 'mega knight', 'zap', 'bandit', 'baby dragon', 'princess', 'arrows', 'archers'],
                 ['p.e.k.k.a', 'mega knight', 'zap', 'bandit', 'baby dragon', 'princess', 'arrows', 'archers'],
                 ['p.e.k.k.a', 'mega knight', 'zap', 'bandit', 'baby dragon', 'princess', 'arrows', 'archers'],
                 ['p.e.k.k.a', 'mega knight', 'zap', 'bandit', 'baby dragon', 'princess', 'arrows', 'archers'],
                 ['p.e.k.k.a', 'mega knight', 'zap', 'bandit', 'baby dragon', 'princess', 'arrows', 'archers'],
                 ['p.e.k.k.a', 'mega knight', 'zap', 'bandit', 'baby dragon', 'princess', 'arrows', 'archers'],
                 ['p.e.k.k.a', 'mega knight', 'zap', 'bandit', 'baby dragon', 'princess', 'arrows', 'archers'],
                 ['p.e.k.k.a', 'mega knight', 'zap', 'bandit', 'baby dragon', 'princess', 'arrows', 'archers'],
                 ['musketeer', 'electro dragon', 'knight', 'battle ram', 'zap', 'wizard', 'guards', 'mirror'],
                 ['p.e.k.k.a', 'mega knight', 'zap', 'bandit', 'baby dragon', 'princess', 'arrows', 'archers'],
                 ['p.e.k.k.a', 'mega knight', 'zap', 'bandit', 'baby dragon', 'princess', 'arrows', 'archers'],
                 ['p.e.k.k.a', 'mega knight', 'zap', 'bandit', 'baby dragon', 'princess', 'arrows', 'archers'],
                 ['p.e.k.k.a', 'mega knight', 'zap', 'bandit', 'baby dragon', 'princess', 'arrows', 'archers'],
                 ['p.e.k.k.a', 'mega knight', 'zap', 'bandit', 'baby dragon', 'princess', 'arrows', 'archers'],
                 ['sparky', 'goblin gang', 'zap', 'valkyrie', 'mega knight', 'witch', 'electro wizard',
                  'elite barbarians'],
                 ['rocket', 'princess', 'mirror', 'bats', 'wizard', 'goblin hut', 'mega knight', 'valkyrie'],
                 ['tesla', 'ice wizard', 'skeletons', 'tornado', 'poison', 'valkyrie', 'rocket', 'the log'],
                 ['valkyrie', 'bomber', 'minions', 'arrows', 'prince', 'giant', 'musketeer', 'skeleton army'],
                 ['prince', 'mega knight', 'inferno dragon', 'rascals', 'wizard', 'giant skeleton', 'witch', 'rage'],
                 ['inferno dragon', 'bandit', 'bats', 'zap', 'bomber', 'mega knight', 'rage', 'bomb tower'],
                 ['magic archer', 'rage', 'witch', 'mirror', 'wizard', 'baby dragon', 'p.e.k.k.a', 'prince'],
                 ['baby dragon', 'fireball', 'arrows', 'valkyrie', 'mini p.e.k.k.a', 'tornado', 'wizard',
                  'firecracker'],
                 ['the log', 'zap', 'princess', 'executioner', 'mini p.e.k.k.a', 'minions', 'p.e.k.k.a', 'bandit'],
                 ['the log', 'zap', 'princess', 'executioner', 'mini p.e.k.k.a', 'minions', 'p.e.k.k.a', 'bandit'],
                 ['the log', 'zap', 'princess', 'executioner', 'mini p.e.k.k.a', 'minions', 'p.e.k.k.a', 'bandit'],
                 ['the log', 'zap', 'princess', 'executioner', 'mini p.e.k.k.a', 'minions', 'p.e.k.k.a', 'bandit'],
                 ['baby dragon', 'the log', 'dark prince', 'rage', 'rocket', 'elite barbarians', 'minion horde',
                  'goblin gang'],
                 ['mini p.e.k.k.a', 'wizard', 'mega knight', 'giant skeleton', 'minion horde', 'mirror',
                  'elite barbarians', 'zap'],
                 ['mini p.e.k.k.a', 'p.e.k.k.a', 'wizard', 'bomber', 'witch', 'barbarians', 'minion horde',
                  'electro wizard'],
                 ['skeleton barrel', 'freeze', 'valkyrie', 'rocket', 'knight', 'mirror', 'wizard', 'battle healer'],
                 ['barbarians', 'sparky', 'electro wizard', 'inferno tower', 'wizard', 'hunter', 'the log',
                  'mega knight'],
                 ['prince', 'skeleton army', 'valkyrie', 'minion horde', 'executioner', 'mega knight', 'rocket',
                  'wizard'], ['minions', 'valkyrie', 'mega knight', 'electro wizard', 'zap', 'wizard', 'firecracker',
                              'mini p.e.k.k.a'],
                 ['rage', 'mega knight', 'elite barbarians', 'ice wizard', 'bats', 'princess', 'inferno dragon',
                  'arrows'],
                 ['magic archer', 'fire spirits', 'prince', 'valkyrie', 'battle ram', 'zap', 'royal recruits', 'bats'],
                 ['zap', 'furnace', 'battle ram', 'flying machine', 'wizard', 'valkyrie', 'inferno dragon',
                  'mini p.e.k.k.a'],
                 ['the log', 'dark prince', 'goblin gang', 'bats', 'electro wizard', 'valkyrie', 'executioner',
                  'p.e.k.k.a'],
                 ['bandit', 'electro wizard', 'mega knight', 'skeleton army', 'sparky', 'arrows', 'ice wizard',
                  'prince'],
                 ['skeletons', 'prince', 'zap', 'goblin hut', 'elite barbarians', 'electro dragon', 'executioner',
                  'zappies'],
                 ['mini p.e.k.k.a', 'archers', 'bomber', 'arrows', 'minions', 'spear goblins', 'goblins', 'prince'],
                 ['skeletons', 'prince', 'zap', 'goblin hut', 'elite barbarians', 'electro dragon', 'executioner',
                  'zappies'],
                 ['mega knight', 'electro wizard', 'fireball', 'tornado', 'skeleton army', 'bomber', 'rocket',
                  'wizard'],
                 ['skeletons', 'prince', 'zap', 'goblin hut', 'elite barbarians', 'electro dragon', 'executioner',
                  'zappies'],
                 ['inferno dragon', 'magic archer', 'lumberjack', 'mega knight', 'barbarian barrel', 'ice golem', 'zap',
                  'bats'],
                 ['giant skeleton', 'electro wizard', 'wizard', 'rage', 'inferno tower', 'miner', 'mini p.e.k.k.a',
                  'princess'],
                 ['minion horde', 'wizard', 'firecracker', 'royal recruits', 'lightning', 'baby dragon', 'bomb tower',
                  'bats'],
                 ['mega knight', 'electro wizard', 'witch', 'fireball', 'p.e.k.k.a', 'wizard', 'valkyrie', 'freeze'],
                 ['mirror', 'barbarian hut', 'rocket', 'minion horde', 'barbarians', 'freeze', 'arrows', 'prince'],
                 ['mirror', 'barbarian hut', 'rocket', 'minion horde', 'barbarians', 'freeze', 'arrows', 'prince'],
                 ['mirror', 'barbarian hut', 'rocket', 'minion horde', 'barbarians', 'freeze', 'arrows', 'prince'],
                 ['mirror', 'barbarian hut', 'rocket', 'minion horde', 'barbarians', 'freeze', 'arrows', 'prince'],
                 ['fire spirits', 'dart goblin', 'knight', 'inferno dragon', 'minion horde', 'bomber', 'rage',
                  'lava hound'],
                 ['mirror', 'barbarian hut', 'rocket', 'minion horde', 'barbarians', 'freeze', 'arrows', 'prince'],
                 ['mirror', 'barbarian hut', 'rocket', 'minion horde', 'barbarians', 'freeze', 'arrows', 'prince'],
                 ['mirror', 'barbarian hut', 'rocket', 'minion horde', 'barbarians', 'freeze', 'arrows', 'prince'],
                 ['mirror', 'barbarian hut', 'rocket', 'minion horde', 'barbarians', 'freeze', 'arrows', 'prince'],
                 ['mirror', 'barbarian hut', 'rocket', 'minion horde', 'barbarians', 'freeze', 'arrows', 'prince'],
                 ['mirror', 'barbarian hut', 'rocket', 'minion horde', 'barbarians', 'freeze', 'arrows', 'prince'],
                 ['mirror', 'barbarian hut', 'rocket', 'minion horde', 'barbarians', 'freeze', 'arrows', 'prince'],
                 ['arrows', 'zap', 'bandit', 'p.e.k.k.a', 'electro wizard', 'mini p.e.k.k.a', 'skeleton army',
                  'magic archer'],
                 ['mirror', 'barbarian hut', 'rocket', 'minion horde', 'barbarians', 'freeze', 'arrows', 'prince'],
                 ['mirror', 'barbarian hut', 'rocket', 'minion horde', 'barbarians', 'freeze', 'arrows', 'prince'],
                 ['mirror', 'barbarian hut', 'rocket', 'minion horde', 'barbarians', 'freeze', 'arrows', 'prince'],
                 ['mirror', 'barbarian hut', 'rocket', 'minion horde', 'barbarians', 'freeze', 'arrows', 'prince'],
                 ['prince', 'bandit', 'guards', 'valkyrie', 'electro wizard', 'princess', 'royal ghost', 'wizard'],
                 ['mirror', 'barbarian hut', 'rocket', 'minion horde', 'barbarians', 'freeze', 'arrows', 'prince'],
                 ['mirror', 'barbarian hut', 'rocket', 'minion horde', 'barbarians', 'freeze', 'arrows', 'prince'],
                 ['tesla', 'dart goblin', 'princess', 'valkyrie', 'dark prince', 'fireball', 'wizard', 'witch'],
                 ['mirror', 'barbarian hut', 'rocket', 'minion horde', 'barbarians', 'freeze', 'arrows', 'prince'],
                 ['mirror', 'barbarian hut', 'rocket', 'minion horde', 'barbarians', 'freeze', 'arrows', 'prince'],
                 ['mirror', 'barbarian hut', 'rocket', 'minion horde', 'barbarians', 'freeze', 'arrows', 'prince'],
                 ['skeleton army', 'rascals', 'baby dragon', 'zap', 'bats', 'inferno dragon', 'mega knight', 'witch'],
                 ['mirror', 'barbarian hut', 'rocket', 'minion horde', 'barbarians', 'freeze', 'arrows', 'prince'],
                 ['mirror', 'barbarian hut', 'rocket', 'minion horde', 'barbarians', 'freeze', 'arrows', 'prince'],
                 ['mirror', 'barbarian hut', 'rocket', 'minion horde', 'barbarians', 'freeze', 'arrows', 'prince'],
                 ['mirror', 'barbarian hut', 'rocket', 'minion horde', 'barbarians', 'freeze', 'arrows', 'prince'],
                 ['zap', 'fireball', 'prince', 'elite barbarians', 'lumberjack', 'electro wizard', 'inferno dragon',
                  'mega knight'],
                 ['mirror', 'barbarian hut', 'rocket', 'minion horde', 'barbarians', 'freeze', 'arrows', 'prince'],
                 ['wizard', 'furnace', 'mega knight', 'inferno tower', 'princess', 'rocket', 'firecracker',
                  'minion horde'],
                 ['mini p.e.k.k.a', 'furnace', 'bomber', 'mirror', 'dart goblin', 'p.e.k.k.a', 'wizard', 'lightning'],
                 ['baby dragon', 'prince', 'executioner', 'goblin gang', 'fireball', 'arrows', 'zap', 'freeze'],
                 ['fireball', 'zap', 'executioner', 'mega knight', 'baby dragon', 'p.e.k.k.a', 'witch', 'minions'],
                 ['giant', 'prince', 'fireball', 'lumberjack', 'wizard', 'valkyrie', 'goblin gang', 'witch'],
                 ['night witch', 'ice wizard', 'prince', 'bomber', 'lumberjack', 'minions', 'rocket', 'poison'],
                 ['miner', 'musketeer', 'minion horde', 'lumberjack', 'magic archer', 'the log', 'goblin gang', 'zap'],
                 ['miner', 'musketeer', 'minion horde', 'lumberjack', 'magic archer', 'the log', 'goblin gang', 'zap'],
                 ['miner', 'musketeer', 'minion horde', 'lumberjack', 'magic archer', 'the log', 'goblin gang', 'zap'],
                 ['miner', 'musketeer', 'minion horde', 'lumberjack', 'magic archer', 'the log', 'goblin gang', 'zap'],
                 ['miner', 'musketeer', 'minion horde', 'lumberjack', 'electro wizard', 'the log', 'goblin gang',
                  'zap'], ['zap', 'poison', 'the log', 'fireball', 'arrows', 'freeze', 'rocket', 'lightning'],
                 ['the log', 'lumberjack', 'bandit', 'bats', 'valkyrie', 'p.e.k.k.a', 'wizard', 'electro wizard'],
                 ['the log', 'tesla', 'p.e.k.k.a', 'minions', 'wizard', 'bandit', 'fire spirits', 'lightning'],
                 ['mega knight', 'princess', 'bandit', 'electro wizard', 'night witch', 'the log', 'sparky',
                  'inferno dragon'],
                 ['p.e.k.k.a', 'ice spirit', 'arrows', 'ice wizard', 'inferno dragon', 'electro wizard', 'the log',
                  'lumberjack'],
                 ['valkyrie', 'executioner', 'elite barbarians', 'inferno tower', 'zap', 'skeleton army', 'p.e.k.k.a',
                  'wizard'],
                 ['night witch', 'lumberjack', 'ice wizard', 'inferno tower', 'wizard', 'bats', 'freeze', 'tesla'],
                 ['night witch', 'lumberjack', 'ice wizard', 'inferno tower', 'wizard', 'bats', 'freeze', 'tesla'],
                 ['night witch', 'lumberjack', 'ice wizard', 'inferno tower', 'wizard', 'bats', 'freeze', 'tesla'],
                 ['p.e.k.k.a', 'the log', 'bandit', 'baby dragon', 'valkyrie', 'ice spirit', 'zap', 'electro wizard'],
                 ['ice wizard', 'skeleton army', 'princess', 'the log', 'miner', 'prince', 'minion horde', 'hunter'],
                 ['miner', 'lumberjack', 'wizard', 'archers', 'zap', 'baby dragon', 'elite barbarians',
                  'skeleton army'],
                 ['fireball', 'fisherman', 'mini p.e.k.k.a', 'mega knight', 'inferno dragon', 'valkyrie', 'the log',
                  'baby dragon'],
                 ['mega knight', 'firecracker', 'lumberjack', 'executioner', 'electro wizard', 'furnace',
                  'inferno tower', 'elite barbarians'],
                 ['p.e.k.k.a', 'electro wizard', 'skeleton army', 'the log', 'bats', 'princess', 'zap', 'executioner'],
                 ['wizard', 'bandit', 'p.e.k.k.a', 'electro wizard', 'guards', 'zap', 'minions', 'bomber'],
                 ['lumberjack', 'royal recruits', 'executioner', 'arrows', 'dart goblin', 'bats', 'valkyrie', 'bandit'],
                 ['royal ghost', 'valkyrie', 'skeleton army', 'arrows', 'fireball', 'bats', 'goblin giant',
                  'musketeer'],
                 ['night witch', 'hunter', 'electro wizard', 'minions', 'tornado', 'minion horde', 'magic archer',
                  'valkyrie'],
                 ['electro wizard', 'baby dragon', 'ice wizard', 'tornado', 'archers', 'wizard', 'night witch',
                  'rocket'],
                 ['zap', 'wizard', 'p.e.k.k.a', 'tornado', 'goblin gang', 'executioner', 'mega knight', 'the log'],
                 ['prince', 'mini p.e.k.k.a', 'wizard', 'baby dragon', 'valkyrie', 'minion horde', 'arrows',
                  'skeleton army'],
                 ['minion horde', 'baby dragon', 'tornado', 'fire spirits', 'the log', 'skeleton army', 'zap',
                  'elite barbarians'],
                 ['goblin gang', 'wizard', 'lightning', 'elite barbarians', 'rage', 'witch', 'minion horde', 'mirror'],
                 ['p.e.k.k.a', 'flying machine', 'baby dragon', 'zap', 'wizard', 'bats', 'mini p.e.k.k.a', 'valkyrie'],
                 ['minion horde', 'arrows', 'wizard', 'firecracker', 'elixir collector', 'p.e.k.k.a', 'skeleton army',
                  'freeze'], ['executioner', 'inferno dragon', 'lumberjack', 'the log', 'prince', 'skeleton army',
                              'elite barbarians', 'fire spirits'],
                 ['wall breakers', 'firecracker', 'knight', 'bats', 'electro wizard', 'bandit', 'valkyrie',
                  'dart goblin'],
                 ['inferno dragon', 'goblin gang', 'ice golem', 'fireball', 'electro wizard', 'mega knight',
                  'dart goblin', 'baby dragon'],
                 ['poison', 'baby dragon', 'wizard', 'rocket', 'witch', 'mirror', 'valkyrie', 'minion horde'],
                 ['p.e.k.k.a', 'elite barbarians', 'valkyrie', 'wizard', 'barbarian barrel', 'freeze', 'bomber',
                  'baby dragon'],
                 ['giant skeleton', 'magic archer', 'mega knight', 'minion horde', 'fire spirits', 'fireball', 'wizard',
                  'mirror'], ['sparky', 'knight', 'bats', 'arrows', 'giant skeleton', 'dark prince', 'goblin gang',
                              'inferno dragon'],
                 ['mega minion', 'mini p.e.k.k.a', 'mega knight', 'bats', 'princess', 'the log', 'tesla', 'poison'],
                 ['valkyrie', 'wizard', 'skeleton army', 'prince', 'minion horde', 'mini p.e.k.k.a', 'baby dragon',
                  'the log'],
                 ['mega knight', 'mini p.e.k.k.a', 'electro wizard', 'lightning', 'bomber', 'zap', 'baby dragon',
                  'minions'],
                 ['royal ghost', 'bats', 'musketeer', 'archers', 'valkyrie', 'baby dragon', 'skeleton army',
                  'inferno dragon'],
                 ['tornado', 'mega knight', 'bowler', 'bats', 'magic archer', 'baby dragon', 'electro wizard',
                  'guards'],
                 ['tornado', 'mega knight', 'bowler', 'bats', 'magic archer', 'baby dragon', 'electro wizard',
                  'guards'],
                 ['lightning', 'mega knight', 'witch', 'elite barbarians', 'inferno tower', 'valkyrie', 'arrows',
                  'wizard'],
                 ['skeleton army', 'rascals', 'minion horde', 'witch', 'sparky', 'mini p.e.k.k.a', 'the log', 'wizard'],
                 ['skeleton army', 'rascals', 'minion horde', 'witch', 'sparky', 'mini p.e.k.k.a', 'the log', 'wizard'],
                 ['skeleton army', 'rascals', 'minion horde', 'witch', 'sparky', 'mini p.e.k.k.a', 'the log', 'wizard'],
                 ['skeleton army', 'rascals', 'minion horde', 'witch', 'sparky', 'mini p.e.k.k.a', 'the log', 'wizard'],
                 ['skeleton army', 'rascals', 'minion horde', 'witch', 'sparky', 'mini p.e.k.k.a', 'the log', 'wizard'],
                 ['skeleton army', 'rascals', 'minion horde', 'witch', 'sparky', 'mini p.e.k.k.a', 'the log', 'wizard'],
                 ['skeleton army', 'rascals', 'minion horde', 'witch', 'sparky', 'mini p.e.k.k.a', 'the log', 'wizard'],
                 ['skeleton army', 'rascals', 'minion horde', 'witch', 'sparky', 'mini p.e.k.k.a', 'the log', 'wizard'],
                 ['skeleton army', 'rascals', 'minion horde', 'witch', 'sparky', 'mini p.e.k.k.a', 'the log', 'wizard'],
                 ['skeleton army', 'rascals', 'minion horde', 'witch', 'sparky', 'mini p.e.k.k.a', 'the log', 'wizard'],
                 ['skeleton army', 'rascals', 'minion horde', 'witch', 'sparky', 'mini p.e.k.k.a', 'the log', 'wizard'],
                 ['skeleton army', 'rascals', 'minion horde', 'witch', 'sparky', 'mini p.e.k.k.a', 'the log', 'wizard'],
                 ['skeleton army', 'rascals', 'minion horde', 'witch', 'sparky', 'mini p.e.k.k.a', 'the log', 'wizard'],
                 ['skeleton army', 'rascals', 'minion horde', 'witch', 'sparky', 'mini p.e.k.k.a', 'the log', 'wizard'],
                 ['sparky', 'p.e.k.k.a', 'royal recruits', 'executioner', 'wizard', 'minion horde', 'skeleton army',
                  'mega knight'],
                 ['skeleton army', 'rascals', 'minion horde', 'witch', 'sparky', 'mini p.e.k.k.a', 'the log', 'wizard'],
                 ['skeleton army', 'rascals', 'minion horde', 'witch', 'sparky', 'mini p.e.k.k.a', 'the log', 'wizard'],
                 ['skeleton army', 'rascals', 'minion horde', 'witch', 'sparky', 'mini p.e.k.k.a', 'the log', 'wizard'],
                 ['skeleton army', 'rascals', 'minion horde', 'witch', 'sparky', 'mini p.e.k.k.a', 'the log', 'wizard'],
                 ['lumberjack', 'baby dragon', 'lightning', 'wizard', 'zap', 'mega knight', 'firecracker', 'bandit'],
                 ['skeleton army', 'rascals', 'minion horde', 'witch', 'sparky', 'mini p.e.k.k.a', 'the log', 'wizard'],
                 ['fire spirits', 'p.e.k.k.a', 'witch', 'goblin gang', 'electro wizard', 'the log', 'zap', 'poison'],
                 ['firecracker', 'witch', 'ice wizard', 'fireball', 'mega knight', 'wizard', 'electro wizard',
                  'prince'], ['valkyrie', 'magic archer', 'furnace', 'rage', 'minions', 'bats', 'fireball', 'knight'],
                 ['lumberjack', 'poison', 'furnace', 'battle ram', 'night witch', 'valkyrie', 'musketeer', 'fireball'],
                 ['rocket', 'zap', 'skeleton army', 'valkyrie', 'mirror', 'fire spirits', 'inferno tower',
                  'mini p.e.k.k.a'],
                 ['the log', 'prince', 'valkyrie', 'fireball', 'zap', 'bowler', 'inferno dragon', 'archers'],
                 ['minion horde', 'battle healer', 'princess', 'miner', 'firecracker', 'sparky', 'ice wizard',
                  'royal recruits'],
                 ['bats', 'the log', 'rocket', 'zap', 'electro wizard', 'skeleton army', 'sparky', 'mega knight'],
                 ['mega knight', 'witch', 'bandit', 'minions', 'electro wizard', 'archers', 'arrows', 'fireball'],
                 ['sparky', 'electro wizard', 'skeleton army', 'p.e.k.k.a', 'bats', 'wizard', 'zap', 'lumberjack'],
                 ['electro wizard', 'rage', 'bomber', 'mirror', 'p.e.k.k.a', 'arrows', 'zap', 'skeleton army'],
                 ['p.e.k.k.a', 'wizard', 'zap', 'the log', 'royal ghost', 'fireball', 'arrows', 'musketeer'],
                 ['prince', 'wizard', 'mega knight', 'skeleton army', 'mini p.e.k.k.a', 'baby dragon', 'valkyrie',
                  'witch'],
                 ['princess', 'p.e.k.k.a', 'wizard', 'elixir golem', 'bomber', 'barbarian barrel', 'fireball',
                  'freeze'],
                 ['prince', 'wizard', 'baby dragon', 'fireball', 'arrows', 'valkyrie', 'electro wizard', 'zap'],
                 ['bandit', 'skeleton army', 'mega knight', 'inferno tower', 'zap', 'bats', 'electro wizard', 'wizard'],
                 ['goblin gang', 'electro wizard', 'mirror', 'valkyrie', 'inferno tower', 'rocket', 'arrows',
                  'elixir collector'],
                 ['electro wizard', 'mini p.e.k.k.a', 'minion horde', 'arrows', 'giant skeleton', 'prince', 'witch',
                  'mirror'],
                 ['electro wizard', 'mini p.e.k.k.a', 'minion horde', 'arrows', 'giant skeleton', 'prince', 'witch',
                  'mirror'],
                 ['electro wizard', 'mini p.e.k.k.a', 'minion horde', 'arrows', 'giant skeleton', 'prince', 'witch',
                  'mirror'],
                 ['electro wizard', 'mini p.e.k.k.a', 'minion horde', 'arrows', 'giant skeleton', 'prince', 'witch',
                  'mirror'],
                 ['electro wizard', 'mini p.e.k.k.a', 'minion horde', 'arrows', 'giant skeleton', 'prince', 'witch',
                  'mirror'],
                 ['electro wizard', 'mini p.e.k.k.a', 'minion horde', 'arrows', 'giant skeleton', 'prince', 'witch',
                  'mirror'],
                 ['electro wizard', 'mini p.e.k.k.a', 'minion horde', 'arrows', 'giant skeleton', 'prince', 'witch',
                  'mirror'],
                 ['electro wizard', 'mini p.e.k.k.a', 'minion horde', 'arrows', 'giant skeleton', 'prince', 'witch',
                  'mirror'],
                 ['p.e.k.k.a', 'valkyrie', 'zap', 'fire spirits', 'executioner', 'tornado', 'tesla', 'the log'],
                 ['p.e.k.k.a', 'valkyrie', 'zap', 'fire spirits', 'firecracker', 'tornado', 'tesla', 'the log'],
                 ['mega knight', 'spear goblins', 'musketeer', 'the log', 'inferno tower', 'fireball', 'bats', 'rage'],
                 ['mega knight', 'baby dragon', 'valkyrie', 'electro wizard', 'hunter', 'furnace', 'ice wizard',
                  'lightning'],
                 ['the log', 'electro wizard', 'royal ghost', 'tesla', 'bandit', 'wizard', 'rocket', 'valkyrie'],
                 ['electro wizard', 'bandit', 'wizard', 'valkyrie', 'freeze', 'mega knight', 'baby dragon', 'fireball'],
                 ['mega knight', 'prince', 'bomber', 'skeleton army', 'witch', 'magic archer', 'fireball', 'arrows'],
                 ['rage', 'lumberjack', 'minion horde', 'zap', 'skeleton army', 'lava hound', 'fireball',
                  'inferno tower'],
                 ['mega knight', 'inferno dragon', 'arrows', 'rage', 'valkyrie', 'wizard', 'lightning',
                  'skeleton army'],
                 ['lumberjack', 'fireball', 'wizard', 'minion horde', 'bats', 'skeleton army', 'zap', 'sparky'],
                 ['lumberjack', 'valkyrie', 'mini p.e.k.k.a', 'battle healer', 'executioner', 'wizard', 'barbarians',
                  'elite barbarians'],
                 ['electro dragon', 'mini p.e.k.k.a', 'zap', 'magic archer', 'valkyrie', 'ice wizard', 'goblin giant',
                  'baby dragon'],
                 ['mega knight', 'electro wizard', 'mini p.e.k.k.a', 'princess', 'executioner', 'zap', 'tornado',
                  'ice wizard'],
                 ['skeleton army', 'sparky', 'wizard', 'bats', 'zap', 'mega knight', 'arrows', 'inferno dragon'],
                 ['dark prince', 'furnace', 'bats', 'elite barbarians', 'mini p.e.k.k.a', 'princess', 'mega knight',
                  'witch'], ['goblin cage', 'rocket', 'cannon cart', 'zap', 'mega knight', 'mirror', 'inferno tower',
                             'magic archer'],
                 ['mega knight', 'minion horde', 'the log', 'skeleton army', 'poison', 'executioner', 'mini p.e.k.k.a',
                  'electro wizard'],
                 ['bandit', 'ice spirit', 'bats', 'zap', 'elixir collector', 'p.e.k.k.a', 'mega knight',
                  'electro wizard'],
                 ['p.e.k.k.a', 'guards', 'zap', 'fireball', 'electro wizard', 'baby dragon', 'valkyrie', 'wizard'],
                 ['witch', 'wizard', 'battle ram', 'minion horde', 'mega knight', 'skeleton army', 'clone',
                  'baby dragon'],
                 ['electro wizard', 'sparky', 'firecracker', 'p.e.k.k.a', 'goblin gang', 'bandit', 'tornado',
                  'the log'],
                 ['baby dragon', 'arrows', 'giant skeleton', 'wizard', 'skeleton army', 'bomber', 'zap', 'valkyrie'],
                 ['p.e.k.k.a', 'bandit', 'tornado', 'the log', 'firecracker', 'executioner', 'inferno dragon', 'zap'],
                 ['valkyrie', 'mega knight', 'ice spirit', 'executioner', 'bomber', 'zap', 'fire spirits', 'tornado'],
                 ['valkyrie', 'mega knight', 'ice spirit', 'executioner', 'bomber', 'zap', 'fire spirits', 'tornado'],
                 ['sparky', 'lightning', 'miner', 'ice wizard', 'knight', 'arrows', 'electro wizard', 'witch'],
                 ['valkyrie', 'mega knight', 'ice spirit', 'executioner', 'bomber', 'zap', 'fire spirits', 'tornado'],
                 ['valkyrie', 'mega knight', 'ice spirit', 'executioner', 'bomber', 'zap', 'fire spirits', 'tornado'],
                 ['valkyrie', 'mega knight', 'ice spirit', 'executioner', 'bomber', 'zap', 'fire spirits', 'tornado'],
                 ['valkyrie', 'mega knight', 'ice spirit', 'executioner', 'bomber', 'zap', 'fire spirits', 'tornado'],
                 ['valkyrie', 'executioner', 'ice spirit', 'mega knight', 'bomber', 'zap', 'fire spirits', 'tornado'],
                 ['valkyrie', 'executioner', 'ice spirit', 'mega knight', 'bomber', 'zap', 'fire spirits', 'tornado'],
                 ['mini p.e.k.k.a', 'executioner', 'sparky', 'valkyrie', 'bats', 'the log', 'electro wizard',
                  'princess'],
                 ['bats', 'minion horde', 'furnace', 'baby dragon', 'witch', 'freeze', 'lumberjack', 'mega knight'],
                 ['witch', 'knight', 'mini p.e.k.k.a', 'zap', 'dart goblin', 'mega knight', 'magic archer', 'arrows'],
                 ['valkyrie', 'freeze', 'the log', 'battle ram', 'tornado', 'minion horde', 'dart goblin', 'fireball'],
                 ['wizard', 'the log', 'fire spirits', 'rage', 'elite barbarians', 'archers', 'firecracker', 'zap'],
                 ['zap', 'inferno dragon', 'witch', 'mega knight', 'lumberjack', 'the log', 'electro wizard', 'bats'],
                 ['dark prince', 'p.e.k.k.a', 'magic archer', 'bandit', 'fireball', 'mega minion', 'zap',
                  'minion horde'],
                 ['executioner', 'fireball', 'baby dragon', 'dark prince', 'skeleton army', 'mega knight', 'valkyrie',
                  'firecracker'],
                 ['mortar', 'bandit', 'miner', 'ice wizard', 'zap', 'skeleton army', 'electro wizard', 'bats'],
                 ['goblin giant', 'skeleton barrel', 'hunter', 'magic archer', 'firecracker', 'bandit', 'royal ghost',
                  'rage'], ['dark prince', 'royal ghost', 'bandit', 'barbarian barrel', 'goblin hut', 'baby dragon',
                            'skeleton army', 'poison'],
                 ['minions', 'p.e.k.k.a', 'barbarians', 'poison', 'tombstone', 'ice wizard', 'zap', 'mega minion'],
                 ['prince', 'baby dragon', 'witch', 'arrows', 'musketeer', 'rage', 'skeleton army', 'fireball'],
                 ['valkyrie', 'executioner', 'mini p.e.k.k.a', 'mega knight', 'skeleton army', 'fire spirits', 'wizard',
                  'bats'],
                 ['witch', 'rage', 'archers', 'mega knight', 'mini p.e.k.k.a', 'wizard', 'valkyrie', 'arrows'],
                 ['skeleton army', 'prince', 'giant skeleton', 'rage', 'witch', 'wizard', 'bandit', 'minion horde'],
                 ['barbarians', 'wizard', 'minion horde', 'miner', 'fire spirits', 'furnace', 'freeze', 'heal'],
                 ['skeleton army', 'princess', 'valkyrie', 'inferno dragon', 'the log', 'mini p.e.k.k.a',
                  'magic archer', 'bandit'],
                 ['skeleton army', 'princess', 'valkyrie', 'inferno dragon', 'the log', 'mini p.e.k.k.a',
                  'magic archer', 'bandit'],
                 ['skeleton army', 'princess', 'valkyrie', 'inferno dragon', 'the log', 'mini p.e.k.k.a',
                  'magic archer', 'bandit'],
                 ['giant', 'mega minion', 'electro wizard', 'mini p.e.k.k.a', 'firecracker', 'prince', 'zap',
                  'earthquake'],
                 ['skeleton army', 'princess', 'valkyrie', 'inferno dragon', 'the log', 'mini p.e.k.k.a',
                  'magic archer', 'bandit'],
                 ['skeleton army', 'princess', 'valkyrie', 'inferno dragon', 'the log', 'mini p.e.k.k.a',
                  'magic archer', 'bandit'],
                 ['skeleton army', 'princess', 'valkyrie', 'inferno dragon', 'the log', 'mini p.e.k.k.a',
                  'magic archer', 'bandit'],
                 ['skeleton army', 'princess', 'valkyrie', 'inferno dragon', 'the log', 'mini p.e.k.k.a',
                  'magic archer', 'bandit'],
                 ['firecracker', 'royal ghost', 'p.e.k.k.a', 'mega knight', 'executioner', 'ice wizard', 'magic archer',
                  'bandit'], ['skeleton army', 'princess', 'valkyrie', 'inferno dragon', 'the log', 'mini p.e.k.k.a',
                              'magic archer', 'bandit'],
                 ['skeleton army', 'princess', 'valkyrie', 'inferno dragon', 'the log', 'mini p.e.k.k.a',
                  'magic archer', 'bandit'],
                 ['sparky', 'executioner', 'inferno dragon', 'skeleton army', 'arrows', 'zap', 'mega knight', 'bats'],
                 ['skeleton army', 'princess', 'valkyrie', 'inferno dragon', 'the log', 'mini p.e.k.k.a',
                  'magic archer', 'bandit'],
                 ['skeleton army', 'princess', 'valkyrie', 'inferno dragon', 'the log', 'mini p.e.k.k.a',
                  'magic archer', 'bandit'],
                 ['skeleton army', 'princess', 'valkyrie', 'inferno dragon', 'the log', 'mini p.e.k.k.a',
                  'magic archer', 'bandit'],
                 ['skeleton army', 'princess', 'valkyrie', 'inferno dragon', 'the log', 'mini p.e.k.k.a',
                  'magic archer', 'bandit'],
                 ['bowler', 'skeleton army', 'inferno tower', 'the log', 'princess', 'musketeer', 'electro wizard',
                  'p.e.k.k.a'], ['skeleton army', 'princess', 'valkyrie', 'inferno dragon', 'the log', 'mini p.e.k.k.a',
                                 'magic archer', 'bandit'],
                 ['bomb tower', 'baby dragon', 'fireball', 'freeze', 'minions', 'giant', 'minion horde', 'prince'],
                 ['poison', 'mini p.e.k.k.a', 'minions', 'the log', 'mega knight', 'skeleton army', 'baby dragon',
                  'electro wizard'],
                 ['ice wizard', 'tornado', 'inferno dragon', 'mega knight', 'magic archer', 'giant skeleton',
                  'electro wizard', 'the log'],
                 ['ice wizard', 'executioner', 'the log', 'mini p.e.k.k.a', 'electro wizard', 'p.e.k.k.a', 'bandit',
                  'goblin gang'],
                 ['barbarians', 'sparky', 'lumberjack', 'the log', 'minion horde', 'tornado', 'royal ghost',
                  'electro wizard'],
                 ['wall breakers', 'electro wizard', 'hunter', 'royal ghost', 'mega knight', 'lumberjack',
                  'inferno dragon', 'valkyrie'],
                 ['night witch', 'the log', 'zap', 'bandit', 'mega knight', 'inferno dragon', 'musketeer',
                  'minion horde'],
                 ['fire spirits', 'zap', 'bomber', 'mega knight', 'minion horde', 'prince', 'arrows', 'barbarians'],
                 ['dark prince', 'musketeer', 'bomber', 'bats', 'baby dragon', 'bandit', 'mega knight', 'sparky'],
                 ['dark prince', 'musketeer', 'bomber', 'bats', 'baby dragon', 'bandit', 'mega knight', 'sparky'],
                 ['dark prince', 'musketeer', 'bomber', 'bats', 'baby dragon', 'bandit', 'mega knight', 'sparky'],
                 ['dark prince', 'musketeer', 'bomber', 'bats', 'baby dragon', 'bandit', 'mega knight', 'sparky'],
                 ['dark prince', 'musketeer', 'bomber', 'bats', 'baby dragon', 'bandit', 'mega knight', 'sparky'],
                 ['dark prince', 'musketeer', 'bomber', 'bats', 'baby dragon', 'bandit', 'mega knight', 'sparky'],
                 ['dark prince', 'musketeer', 'bomber', 'bats', 'baby dragon', 'bandit', 'mega knight', 'sparky'],
                 ['valkyrie', 'wizard', 'the log', 'hunter', 'royal ghost', 'skeleton army', 'rocket', 'cannon cart'],
                 ['dark prince', 'musketeer', 'bomber', 'bats', 'baby dragon', 'bandit', 'mega knight', 'sparky'],
                 ['mega knight', 'baby dragon', 'lumberjack', 'zap', 'fire spirits', 'royal ghost', 'bandit',
                  'firecracker'],
                 ['dark prince', 'musketeer', 'bomber', 'bats', 'baby dragon', 'bandit', 'mega knight', 'sparky'],
                 ['bats', 'electro dragon', 'baby dragon', 'sparky', 'clone', 'mega knight', 'mirror', 'ice golem'],
                 ['dark prince', 'musketeer', 'bomber', 'bats', 'baby dragon', 'bandit', 'mega knight', 'sparky'],
                 ['dark prince', 'musketeer', 'bomber', 'bats', 'baby dragon', 'bandit', 'mega knight', 'sparky'],
                 ['dark prince', 'musketeer', 'bomber', 'bats', 'baby dragon', 'bandit', 'mega knight', 'sparky'],
                 ['mega knight', 'elixir golem', 'electro wizard', 'firecracker', 'p.e.k.k.a', 'mini p.e.k.k.a',
                  'wizard', 'mirror'],
                 ['dark prince', 'musketeer', 'bomber', 'bats', 'baby dragon', 'bandit', 'mega knight', 'sparky'],
                 ['dark prince', 'musketeer', 'bomber', 'bats', 'baby dragon', 'bandit', 'mega knight', 'sparky'],
                 ['dark prince', 'musketeer', 'bomber', 'bats', 'baby dragon', 'bandit', 'mega knight', 'sparky'],
                 ['wizard', 'minion horde', 'mirror', 'bomb tower', 'barbarians', 'elite barbarians', 'rocket',
                  'bomber'],
                 ['dark prince', 'musketeer', 'bomber', 'bats', 'baby dragon', 'bandit', 'mega knight', 'sparky'],
                 ['dark prince', 'musketeer', 'bomber', 'bats', 'baby dragon', 'bandit', 'mega knight', 'sparky'],
                 ['dark prince', 'musketeer', 'bomber', 'bats', 'baby dragon', 'bandit', 'mega knight', 'sparky'],
                 ['dark prince', 'musketeer', 'bomber', 'bats', 'baby dragon', 'bandit', 'mega knight', 'sparky'],
                 ['dark prince', 'musketeer', 'bomber', 'bats', 'baby dragon', 'bandit', 'mega knight', 'sparky'],
                 ['dark prince', 'musketeer', 'bomber', 'bats', 'baby dragon', 'bandit', 'mega knight', 'sparky'],
                 ['dark prince', 'musketeer', 'bomber', 'bats', 'baby dragon', 'bandit', 'mega knight', 'sparky'],
                 ['dark prince', 'musketeer', 'bomber', 'bats', 'baby dragon', 'bandit', 'mega knight', 'sparky'],
                 ['valkyrie', 'witch', 'fireball', 'wizard', 'the log', 'zap', 'elite barbarians', 'rage'],
                 ['dark prince', 'musketeer', 'bomber', 'bats', 'baby dragon', 'bandit', 'mega knight', 'sparky'],
                 ['giant skeleton', 'princess', 'poison', 'firecracker', 'mega minion', 'mega knight', 'tesla', 'zap'],
                 ['prince', 'ice golem', 'miner', 'the log', 'minions', 'zap', 'fire spirits', 'tesla'],
                 ['bandit', 'skeleton army', 'electro wizard', 'bomber', 'musketeer', 'knight', 'wizard', 'lightning'],
                 ['magic archer', 'mega knight', 'valkyrie', 'firecracker', 'skeletons', 'ice spirit', 'sparky', 'zap'],
                 ['bandit', 'skeleton army', 'electro wizard', 'bomber', 'musketeer', 'knight', 'wizard', 'lightning'],
                 ['mega knight', 'electro wizard', 'the log', 'valkyrie', 'skeleton army', 'sparky', 'zap', 'bandit'],
                 ['bandit', 'skeleton army', 'electro wizard', 'bomber', 'musketeer', 'knight', 'wizard', 'lightning'],
                 ['rocket', 'wizard', 'dark prince', 'arrows', 'minion horde', 'skeleton army', 'fire spirits',
                  'valkyrie'],
                 ['bandit', 'skeleton army', 'electro wizard', 'bomber', 'musketeer', 'knight', 'wizard', 'lightning'],
                 ['bandit', 'skeleton army', 'electro wizard', 'bomber', 'musketeer', 'knight', 'wizard', 'lightning'],
                 ['sparky', 'mirror', 'electro wizard', 'prince', 'rocket', 'mini p.e.k.k.a', 'mega knight', 'wizard'],
                 ['bandit', 'skeleton army', 'electro wizard', 'bomber', 'musketeer', 'knight', 'wizard', 'lightning'],
                 ['bandit', 'skeleton army', 'electro wizard', 'bomber', 'musketeer', 'knight', 'wizard', 'lightning'],
                 ['bandit', 'skeleton army', 'electro wizard', 'bomber', 'musketeer', 'knight', 'wizard', 'lightning'],
                 ['bandit', 'skeleton army', 'electro wizard', 'bomber', 'musketeer', 'knight', 'wizard', 'lightning'],
                 ['bandit', 'skeleton army', 'electro wizard', 'bomber', 'musketeer', 'knight', 'wizard', 'lightning'],
                 ['mirror', 'inferno tower', 'knight', 'electro wizard', 'mini p.e.k.k.a', 'arrows', 'princess',
                  'wizard'],
                 ['bandit', 'skeleton army', 'electro wizard', 'bomber', 'musketeer', 'knight', 'wizard', 'lightning'],
                 ['bandit', 'skeleton army', 'electro wizard', 'bomber', 'musketeer', 'knight', 'wizard', 'lightning'],
                 ['bandit', 'skeleton army', 'electro wizard', 'bomber', 'musketeer', 'knight', 'wizard', 'lightning'],
                 ['bandit', 'skeleton army', 'electro wizard', 'bomber', 'musketeer', 'knight', 'wizard', 'lightning'],
                 ['bandit', 'skeleton army', 'electro wizard', 'bomber', 'musketeer', 'knight', 'wizard', 'lightning'],
                 ['bandit', 'skeleton army', 'electro wizard', 'bomber', 'musketeer', 'knight', 'wizard', 'lightning'],
                 ['bandit', 'skeleton army', 'electro wizard', 'bomber', 'musketeer', 'knight', 'wizard', 'lightning'],
                 ['baby dragon', 'valkyrie', 'barbarians', 'skeleton army', 'wizard', 'mega knight', 'magic archer',
                  'executioner'],
                 ['bandit', 'skeleton army', 'electro wizard', 'bomber', 'musketeer', 'knight', 'wizard', 'lightning'],
                 ['bandit', 'skeleton army', 'electro wizard', 'bomber', 'musketeer', 'knight', 'wizard', 'poison'],
                 ['bandit', 'skeleton army', 'electro wizard', 'bomber', 'musketeer', 'knight', 'wizard', 'poison'],
                 ['bandit', 'skeleton army', 'electro wizard', 'bomber', 'musketeer', 'knight', 'wizard', 'poison'],
                 ['bandit', 'skeleton army', 'electro wizard', 'bomber', 'musketeer', 'knight', 'wizard', 'poison'],
                 ['fireball', 'minion horde', 'prince', 'barbarians', 'mirror', 'firecracker', 'bomber', 'wizard'],
                 ['bandit', 'skeleton army', 'electro wizard', 'bomber', 'musketeer', 'knight', 'wizard', 'poison']]
# lUnknownDecks = [['a','b','c','d','e','f','g','h','i'],['a','b','c','d','e','f','g','h','i'],['x','b','c'],['x','b','c'],['z','b','c']]
print(len(lUnknownDecks), lUnknownDecks)
arr_unique = makeunique_multi(lUnknownDecks)
print(len(arr_unique), arr_unique)
arr_print = [i + [(lUnknownDecks.count(i))] for i in arr_unique]
list.sort(arr_print, key=lambda arr_print: arr_print[len(arr_print) - 1], reverse=True)
print(len(arr_print), arr_print)
with open('unknown_decks.csv', 'w+', newline='') as my_csv:
    csvWriter = csv.writer(my_csv, delimiter=',')
    try:
        csvWriter.writerows(arr_print)
    except:
        pass
